---
sidebar: sidebar
permalink: task_dc_openstack.html
keywords: data collector, openstack, OpenStack 
summary: OpenStack data collector.
---

= OpenStack data collector

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead] 

The OpenStack (REST API / KVM) data collector acquires inventory data for all OpenStack instances, and optionally, VM performance data. 

== Requirements

* IP address of the OpenStack controller 
* OpenStack admin role credential and sudo access to the Linux KVM hypervisor. If you are not using the admin account or admin equivalent privileges, you will need to use trial and error to identify the default policies to relax for your data collector userid.  
* The OpenStack Ceilometer module must be installed and configured for performance collection. Configuring the Ceilometer is done by editing the nova.conf file for each hypervisor and then restarting the Nova Compute service on each hypervisor. The option name changes for different releases of OpenStack:
** Icehouse
** Juno
** Kilo
** Liberty
** Mitaka
** Newton
** Ocata
* For CPU stats, “compute_monitors=ComputeDriverCPUMonitor” needs to be turned on in /etc/nova/nova.conf on compute nodes. 
* Port requirements:
** 5000 for http and 13000 for https, for the Keystone service 
** 22 for KVM SSH 
** 8774 for Nova Compute Service 
** 8776 for Cinder Block Service 
** 8777 for Ceilometer Performance Service 
** 9292 for Glance Image Service 
*Note* The port binds to the specific service, and the service may run on the controller or another host in larger environments. 

== Configuration

By default, only admin users can access the OpenStack REST APIs which Cloud Insights uses to collect data from Openstack. However, the Cloud Insights OpenStack data collector can use a non-admin user role to be able to collect data from the cluster. To allow this, you must modify the policy file for the OpenStack Nova service to allow users other than admin to make the REST calls. For advanced policy configurations, please refer to the link:https://docs.openstack.org/oslo.policy/latest/admin/policy-json-file.html[*Openstack documentation*]. 

Follow these steps to allow non-admin user to make the RESt API calls:

. Log in to the OpenStack controller. 
. Use text editor to open /etc/nova/policy.json and add the following.

 {
                 "os_compute_api:os-availability-zone:detail": "",
                 "os_compute_api:os-hypervisors": "",
                 "os_compute_api:servers:detail:get_all_tenants": "",
 }

. Restart the Nova service:

 systemctl restart openstack-nova-api.service



[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
| OpenStack Controller IP Address|IP address or fully-qualified domain name of the OpenStack Controller 
|OpenStack Administrator|User name for an OpenStack Admin
|OpenStack Password|Password used for the OpenStack Admin
|OpenStack Administrator Tenant|OpenStack Administrator Tenant name
|KVM Sudo User|KVM Sudo User name
|Choose 'Password' or 'OpenSSH Key File' to specify credential type|Credential type used to connect to the device via SSH
|Full Path to Inventory Private Key|Full Path to Inventory Private Key
|KVM Sudo Password |KVM Sudo Password
|===

== Advanced configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Enable hypervisor inventory discovery through SSH|Check this to enable hypervisor inventory discovery through SSH 
|OpenStack Admin URL port|OpenStack Admin URL port
|Use HTTPS|Check to use secure HTTP
//|HTTP Connection Timeout (sec)|Timeout for HTTP connection. The default is 300 seconds.
|SSH Port|Port used for SSH
//|SSH Process Wait Timeout (sec)|SSH process timeout. The default is 30 seconds.
|SSH Process Retries|Number of inventory retry attempts
|Inventory Poll Interval (min)|Interval between inventory polls.  The default is 20 minutes.
|===

== Troubleshooting
Some things to try if you encounter problems with this data collector:

==== Inventory

[cols=2*, options="header", cols"50,50"]
|===
|Problem:|Try this:
|"Configuration error" with error messages start with “Policy doesn't allow” or “You are not authorized”
| * Check ip address
* Check User name and password
|===

Additional information may be found from the link:concept_requesting_support.html[Support] page or in the link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf[Data Collector Support Matrix].

